apiVersion: extensions/v1beta1
kind: Deployment                          
metadata:
  name: docker-druid                                  
  namespace: td-data                                 
spec:
  replicas: 1                                  
  template:                                        
    metadata:
      labels:                                      
        app: docker-druid
    spec:
      volumes:
        - name: "opt"
          hostPath:  
            path: "/dt/nfs/druid/opt",
            type: Directory
        - name: "tmp"
          hostPath:  
            path: "/dt/nfs/druid/tmp",
            type: Directory
      volumeMounts:
        - name:  "opt"
          mountPath:  "/opt/druid/var"
        - name:  "/tmp"
          mountPath:  "/tmp"
      hostAliases:
      - ip: "192.168.8.207"
        hostnames:
        - "dt-master"
      containers:                                  
      - name: druid
        image: registry.cn-hangzhou.aliyuncs.com/thundersdata-public/docker-druid:hdfs
        imagePullPolicy: Always
        ports:
        - name: coordinator
          containerPort: 8081                                                                  
        - name: broker
          containerPort: 8082                                                                  
        - name: historical
          containerPort: 8083                                                                  
        - name: overlord
          containerPort: 8090                                                                  
        - name: router
          containerPort: 8888                                                                  
---
apiVersion: v1
kind: Service
metadata:
  name: docker-druid
  labels:
    app: docker-druid  
  namespace: td-data
spec:                                             
  ports:
      - name: coordinator
        port: 8081                                                                  
        targetPort: 8081                                                                  
      - name: broker
        port: 8082                                                                  
        targetPort: 8082                                                                  
      - name: historical
        port: 8083                                                                  
        targetPort: 8083                                                                  
      - name: overlord
        port: 8090                                                                  
        targetPort: 8090                                                                  
      - name: router
        port: 8888                                                                  
        targetPort: 8888                                                                  
  type: NodePort
  selector:      
   app: docker-druid
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: docker-druid
  namespace: td-data
  labels:
    k8s-app: docker-druid
  annotations:
    configuration.konghq.com: configuration-kongingress
spec:
  rules:
  - host: docker-druid.sw.thundersdata.com
    http:
      paths:
      - path: "/"
        backend:
          serviceName: docker-druid
          servicePort: 8888