apiVersion: extensions/v1beta1
kind: Deployment                          
metadata:
  name: docker-druid                                  
  namespace: td-data                                 
spec:
  replicas: 1                                  
  template:                                        
    metadata:
      labels:                                      
        app: docker-druid
    spec:
      containers:                                  
      - name: druid
        image: fokkodriesprong/docker-druid:version-0.16.0
        ports:
        - name: coordinator
          containerPort: 8081                                                                  
        - name: broker
          containerPort: 8082                                                                  
        - name: historical
          containerPort: 8083                                                                  
        - name: overlord
          containerPort: 8090                                                                  
        - name: router
          containerPort: 8888                                                                  
---
apiVersion: v1
kind: Service
metadata:
  name: docker-druid
  labels:
    app: docker-druid  
  namespace: td-data
spec:                                             
  ports:
      - name: coordinator
        port: 8081                                                                  
        targetPort: 8081                                                                  
      - name: broker
        port: 8082                                                                  
        targetPort: 8082                                                                  
      - name: historical
        port: 8083                                                                  
        targetPort: 8083                                                                  
      - name: overlord
        port: 8090                                                                  
        targetPort: 8090                                                                  
      - name: router
        port: 8888                                                                  
        targetPort: 8888                                                                  
  type: NodePort
  selector:      
   app: docker-druid