CREATE TABLE `pharmacy`.`wide_pharmacy_sales_2019_druid`(
  `subfhd_fid` double, 
  `subfhd_fyear` double, 
  `subfhd_djlx` double, 
  `subfhd_fperiod` double, 
  `subfhd_ftype` double, 
  `subfhd_jzbz` double, 
  `subfhd_shbz` double, 
  `subfhd_lsh` varchar(50), 
  `subfhd_kdrq` date, 
  `subfhd_subbh` varchar(30), 
  `subfhd_dh` varchar(300), 
  `subfhd_lb` varchar(30), 
  `subfhd_hh` varchar(30), 
  `subfhd_zzsl` double, 
  `subfhd_sl` double, 
  `subfhd_zk` double, 
  `subfhd_dj` double, 
  `subfhd_lsj` double, 
  `subfhd_sj` double, 
  `subfhd_je` double, 
  `subfhd_se` double, 
  `subfhd_jshj` double, 
  `subfhd_cbj` double, 
  `subfhd_cbe` double, 
  `subfhd_ml` double, 
  `subfhd_lsze` double, 
  `subfhd_cj` double, 
  `subfhd_xsr` varchar(100), 
  `subfhd_bz` varchar(100), 
  `subfhd_czry` varchar(30), 
  `subfhd_ph1` varchar(30), 
  `subfhd_ph2` varchar(30), 
  `subfhd_ph3_sl` double, 
  `subfhd_ph1_xq` date, 
  `subfhd_fvchnum` double, 
  `subfhd_fgroup` varchar(30), 
  `subfhd_fvch` double, 
  `subfhd_stockid` varchar(30), 
  `subfhd_bm` varchar(30), 
  `subfhd_yhkh` varchar(30), 
  `subfhd_pcdh` varchar(300), 
  `subfhd_fpzdate` date, 
  `subfhd_fpzperiod` double, 
  `subfhd_fpzyear` double, 
  `subfhd_vchoperation` varchar(30), 
  `subfhd_fvchid` varchar(30), 
  `subfhd_jzry` varchar(50), 
  `subfhd_commissionrate` double, 
  `subfhd_scrq` date, 
  `subfhd_batchprice` double, 
  `subfhd_billtime` varchar(20), 
  `subfhd_jzrq` date, 
  `subfhd_balancebaseprice` double, 
  `subfhd_integralvalue` double, 
  `subfhd_posguid` varchar(50), 
  `subfhd_dealguid` varchar(50), 
  `subfhd_daliylogdate` date, 
  `subfhd_customerinfo` varchar(50), 
  `subfhd_zblastpurchaseprice` double, 
  `subfhd_zbjhdj` double, 
  `subfhd_headbatchnumber` varchar(50), 
  `subfhd_suppliercode` varchar(50), 
  `subfhd_cxfaid` varchar(50), 
  `subfhd_pfml` double, 
  `subfhd_hsml` double, 
  `subfhd_rightoptcode` varchar(50), 
  `subfhd_workshiftid` varchar(50), 
  `subfhd_tcfs` varchar(10), 
  `subfhd_cxfamxid` varchar(50), 
  `subfhd_kh` varchar(30), 
  `subfhd_policytype` double, 
  `subfhd_fsfcj` double, 
  `subfhd_cdbz` double, 
  `subfhd_personname` varchar(30), 
  `subfhd_idcardno` varchar(30), 
  `subfhd_boxid` varchar(50), 
  `subfhd_checknum` double, 
  `subfhd_isrecheck` double, 
  `subfhd_recheckdate` date, 
  `subfhd_recheckoperatorguid` varchar(50), 
  `subfhd_tjbh` varchar(100), 
  `subfhd_auditingname` varchar(50), 
  `subfhd_patientname` varchar(50), 
  `subfhd_doctorname` varchar(50), 
  `subfhd_doctorcode` varchar(50), 
  `subfhd_clname` varchar(50), 
  `subfhd_pharmacistname` varchar(50), 
  `subfhd_appdetailguid` varchar(50), 
  `subfhd_appguid` varchar(50), 
  `subfhd_c_ys` varchar(50), 
  `subfhd_c_cfh` varchar(50), 
  `subfhd_posname` varchar(20), 
  `subfhd_omsbz` varchar(10), 
  `yw_kck_lb` varchar(30), 
  `yw_kck_hh` varchar(50), 
  `yw_kck_pm` varchar(80), 
  `yw_kck_bm` varchar(80), 
  `yw_kck_cd` varchar(150), 
  `yw_kck_dwbh` varchar(30), 
  `yw_kck_dwmc` varchar(80), 
  `yw_kck_gg` varchar(80), 
  `yw_kck_pdw` varchar(30), 
  `yw_kck_yblb` varchar(200), 
  `yw_kck_mjl` double, 
  `yw_kck_mjzl` varchar(80), 
  `yw_kck_jj` double, 
  `yw_kck_jj_ckj` double, 
  `yw_kck_ckj` double, 
  `yw_kck_pfj` double, 
  `yw_kck_lsj` double, 
  `yw_kck_cbj` double, 
  `yw_kck_ycbj` double, 
  `yw_kck_lastbalanceprice` double, 
  `yw_kck_sjsl` double, 
  `yw_kck_xhsl` double, 
  `yw_kck_xh` double, 
  `yw_kck_jhsl` double, 
  `yw_kck_qtfcsl` double, 
  `yw_kck_qtsrsl` double, 
  `yw_kck_max_sl` double, 
  `yw_kck_min_sl` double, 
  `yw_kck_dy_tag` double, 
  `yw_kck_tj_tag` double, 
  `yw_kck_hs_tag` double, 
  `yw_kck_ckj_tag` double, 
  `yw_kck_zy` varchar(100), 
  `yw_kck_xq_date` date, 
  `yw_kck_jh_date` date, 
  `yw_kck_xh_date` date, 
  `yw_kck_pfj1` double, 
  `yw_kck_sj` double, 
  `yw_kck_ls_jj1` double, 
  `yw_kck_ls_jj2` double, 
  `yw_kck_ls_jj3` double, 
  `yw_kck_kh` varchar(30), 
  `yw_kck_zk` double, 
  `yw_kck_zzsl` double, 
  `yw_kck_pm_zjm` varchar(30), 
  `yw_kck_bz` varchar(100), 
  `yw_kck_hh_tmp` varchar(30), 
  `yw_kck_sjsl_ls` double, 
  `yw_kck_tcbl1` double, 
  `yw_kck_tcbl2` double, 
  `yw_kck_tcbl3` double, 
  `yw_kck_ph1` varchar(30), 
  `yw_kck_ph2` varchar(30), 
  `yw_kck_ph3` varchar(30), 
  `yw_kck_zyc_tag` double, 
  `yw_kck_zzrs_tag` double, 
  `yw_kck_ph3_sl` double, 
  `yw_kck_lsj1` double, 
  `yw_kck_bzsl` double, 
  `yw_kck_sj1` double, 
  `yw_kck_tm` varchar(30), 
  `yw_kck_pj` double, 
  `yw_kck_pdsl` double, 
  `yw_kck_sysl` double, 
  `yw_kck_sx` varchar(30), 
  `yw_kck_spid` varchar(30), 
  `yw_kck_sfcf` double, 
  `yw_kck_pzwh` varchar(100), 
  `yw_kck_scdw` varchar(150), 
  `yw_kck_scrq` date, 
  `yw_kck_zcsb` varchar(100), 
  `yw_kck_jjff` varchar(30), 
  `yw_kck_fdeleted` double, 
  `yw_kck_sx1` varchar(30), 
  `yw_kck_sx2` varchar(30), 
  `yw_kck_dwmc1` varchar(80), 
  `yw_kck_dwmc2` varchar(80), 
  `yw_kck_jx` varchar(30), 
  `yw_kck_ysbz` varchar(80), 
  `yw_kck_cctj` varchar(100), 
  `yw_kck_tybz` double, 
  `yw_kck_sybz` double, 
  `yw_kck_dls` varchar(80), 
  `yw_kck_bzgg` varchar(30), 
  `yw_kck_bz1` varchar(100), 
  `yw_kck_bz2` varchar(100), 
  `yw_kck_bz3` varchar(100), 
  `yw_kck_bz4` varchar(100), 
  `yw_kck_bz5` varchar(100), 
  `yw_kck_bzbz` double, 
  `yw_kck_bzhh` varchar(30), 
  `yw_kck_bzl` double, 
  `yw_kck_zbzl` double, 
  `yw_kck_kcspid` varchar(30), 
  `yw_kck_xssrid` varchar(30), 
  `yw_kck_xscbid` varchar(30), 
  `yw_kck_km1` varchar(30), 
  `yw_kck_km2` varchar(30), 
  `yw_kck_km3` varchar(30), 
  `yw_kck_km4` varchar(30), 
  `yw_kck_km5` varchar(30), 
  `yw_kck_fonlymoney` double, 
  `yw_kck_fisybpz` double, 
  `yw_kck_fisgmp` double, 
  `yw_kck_scrqrequest` double, 
  `yw_kck_yxqrequest` double, 
  `yw_kck_tcbl` double, 
  `yw_kck_fisrecipe` double, 
  `yw_kck_fsjbl` double, 
  `yw_kck_ftsbz` double, 
  `yw_kck_hyj` double, 
  `yw_kck_iscolorsize` double, 
  `yw_kck_noabate` double, 
  `yw_kck_c_gx` varchar(1000), 
  `yw_kck_c_xz` varchar(1000), 
  `yw_kck_c_yhly` varchar(50), 
  `yw_kck_c_zdyh` double, 
  `yw_kck_guid` varchar(50), 
  `yw_kck_createdate` date, 
  `yw_kck_updatedate` date, 
  `yw_kck_c_ypfl` varchar(50), 
  `yw_kck_stocktaxrate` double, 
  `yw_kck_materieldiscountrateid` varchar(50), 
  `yw_kck_gspsortid` varchar(50), 
  `yw_kck_materielimage` binary, 
  `yw_kck_iscourtesycard` double, 
  `yw_kck_courtesycardtypeid` varchar(50), 
  `yw_kck_parvalue` double, 
  `yw_kck_issalespromotion` double, 
  `yw_kck_inoutstatus` double, 
  `yw_kck_branchguid` varchar(50), 
  `yw_kck_fdate` date, 
  `yw_kck_bh` varchar(30), 
  `yw_kck_ghqy` varchar(50), 
  `yw_kck_gmpzsh` varchar(50), 
  `yw_kck_gmprzrq` date, 
  `yw_kck_gmprzxq` date, 
  `yw_kck_ccjybgs` varchar(80), 
  `yw_kck_syjybgs` varchar(80), 
  `yw_kck_syjyjl` varchar(100), 
  `yw_kck_cgyy` varchar(200), 
  `yw_kck_cgy` varchar(30), 
  `yw_kck_yj_yw` varchar(100), 
  `yw_kck_jl_yw` varchar(30), 
  `yw_kck_rq_yw` date, 
  `yw_kck_yj_zg` varchar(100), 
  `yw_kck_jl_zg` varchar(30), 
  `yw_kck_rq_zg` date, 
  `yw_kck_yj_wj` varchar(100), 
  `yw_kck_jl_wj` varchar(30), 
  `yw_kck_rq_wj` date, 
  `yw_kck_yj_jl` varchar(100), 
  `yw_kck_ypqk` varchar(200), 
  `yw_kck_zyx1` varchar(50), 
  `yw_kck_zyx2` varchar(50), 
  `yw_kck_zyx3` varchar(50), 
  `yw_kck_zyx4` varchar(50), 
  `yw_kck_hgbz` double, 
  `yw_kck_spry` varchar(30), 
  `yw_kck_bqsms` varchar(200), 
  `yw_kck_wcbz` double, 
  `yw_kck_gjxj` double, 
  `yw_kck_ckjj` double, 
  `yw_kck_gys` varchar(30), 
  `yw_kck_gyslb` varchar(30), 
  `yw_kck_gysdb` varchar(30), 
  `yw_kck_sqwtqx` date, 
  `yw_kck_ckgl` varchar(50), 
  `yw_kck_gndls` varchar(50), 
  `yw_kck_jkzczh` varchar(50), 
  `yw_kck_jkka` varchar(50), 
  `yw_kck_xkzqx` date, 
  `yw_kck_yhcs` varchar(50), 
  `yw_kck_wjpw` varchar(50), 
  `yw_kck_ypbz` double, 
  `yw_kck_ysrkyxqbz` double, 
  `yw_kck_cmdjcbz` double, 
  `yw_kck_syystxbz` double, 
  `yw_kck_yszdbz` double, 
  `yw_kck_srysfhbz` double, 
  `yw_kck_bcyhyjfbz` double, 
  `yw_kck_xpzgzbz` double, 
  `yw_kck_xpzgzqx` date, 
  `yw_kck_lsjgllb` varchar(30), 
  `yw_kck_cgxj` double, 
  `yw_kck_cgjccgxjbz` double, 
  `yw_kck_xjsbz` double, 
  `yw_kck_rjksxbz` double, 
  `yw_kck_kcsx` double, 
  `yw_kck_kcxx` double, 
  `yw_kck_xjkxxbz` double, 
  `yw_kck_abcflsx` varchar(50), 
  `yw_kck_ztflsx` varchar(50), 
  `yw_kck_fzflsx1` varchar(50), 
  `yw_kck_fzflsx2` varchar(50), 
  `yw_kck_fzflsx3` varchar(50), 
  `yw_kck_fzflsx4` varchar(50), 
  `yw_kck_fzflsx5` varchar(50), 
  `yw_kck_isauditing` double, 
  `yw_kck_iscancel` double, 
  `yw_kck_lxtjbh` varchar(50), 
  `yw_kck_salechannel` varchar(100), 
  `yw_kck_salearea` varchar(100), 
  `yw_kck_operatorguid` varchar(50), 
  `yw_kck_auditingguid` varchar(50), 
  `yw_kck_djzt` double, 
  `yw_kck_vipintegraltype` varchar(50), 
  `yw_kck_isnebalance` double, 
  `yw_kck_auditingdate` date, 
  `yw_kck_jkpzbz` double, 
  `yw_kck_zybz` double, 
  `yw_kck_lspszbz_tag` double, 
  `yw_kck_largepackunit` varchar(50), 
  `yw_kck_largepackbarcode` varchar(50), 
  `yw_kck_middlepackunit` varchar(50), 
  `yw_kck_middlepackbarcode` varchar(50), 
  `yw_kck_balanceproperty` double, 
  `yw_kck_medicalinstrumenttype` varchar(50), 
  `yw_kck_iseggpreparation` double, 
  `yw_kck_istwoclassmentaldrug` double, 
  `yw_kck_isephedrine` double, 
  `yw_kck_istlhormone` double, 
  `yw_kck_isminddrug` double, 
  `yw_kck_isdangerchemistry` double, 
  `yw_kck_materialimage` binary, 
  `yw_kck_groupcontrolpurtype` varchar(50), 
  `yw_kck_ispick` double, 
  `yw_kck_autocode` varchar(50), 
  `yw_kck_smallpackage` double, 
  `yw_kck_smallpackunit` varchar(50), 
  `yw_kck_smallpackagebarcode` varchar(50), 
  `yw_kck_isanaesthetic` double, 
  `yw_kck_ismedicaltoxicity` double, 
  `yw_kck_isvaccine` double, 
  `yw_kck_isdiagnosticreagent` double, 
  `yw_kck_isstimulant` double, 
  `yw_kck_shyb` double, 
  `yw_kck_syb` double, 
  `yw_kck_tlb` double, 
  `yw_kck_iscontrolsellscope` double, 
  `yw_kck_financetype` varchar(50), 
  `yw_kck_grouppurchbranchguid` varchar(50), 
  `yw_kck_purchasebalance` double, 
  `yw_kck_c_yongzi` double, 
  `yw_kck_stockid` varchar(50), 
  `yw_kck_ysry` varchar(50), 
  `yw_kck_ysywy` varchar(50), 
  `yw_kck_storeman` varchar(50), 
  `yw_kck_cd_zjm` varchar(150), 
  `yw_kck_isselectbatch` double, 
  `yw_kck_brandattribute` varchar(50), 
  `yw_kck_grossratetype` varchar(50), 
  `yw_kck_reservelistcode` varchar(50), 
  `yw_kck_historycode` varchar(50), 
  `yw_kck_salespromotiontypeid` varchar(50), 
  `yw_kck_wmsisexport` double, 
  `yw_kck_wmsrecordstatus` double, 
  `yw_kck_wmsexportcount` double, 
  `yw_kck_wmsexportdate` date, 
  `yw_kck_ismonitor` double, 
  `yw_kck_isean1` double, 
  `yw_kck_isean2` double, 
  `yw_kck_trayquantity` double, 
  `yw_kck_islowtemperature` double, 
  `yw_kck_takemoneytype` varchar(50), 
  `yw_kck_isgift` double, 
  `yw_kck_pricebelttype` varchar(50), 
  `yw_kck_basematerielretailprice` double, 
  `yw_kck_promanageretailprice` double, 
  `yw_kck_materielstatus` varchar(100), 
  `yw_kck_coreitemsclass` varchar(100), 
  `yw_kck_seasonclass` varchar(100), 
  `yw_kck_arearangedescibeid` varchar(100), 
  `yw_kck_arearangedescibe` varchar(1000), 
  `yw_kck_materieldescawakeid` varchar(100), 
  `yw_kck_materieldescawake` varchar(1000), 
  `yw_kck_forbiddenreason` varchar(200), 
  `yw_kck_stoppurchasereason` varchar(200), 
  `yw_kck_pzwhxq` date, 
  `yw_kck_zzqx` date, 
  `yw_kck_yyzyxkzxq` varchar(100), 
  `yw_kck_ishealthfoods` double, 
  `yw_kck_issellsplitsmallpack` double, 
  `yw_kck_isrecordbiglsh` double, 
  `yw_kck_comparebillno` varchar(50), 
  `yw_kck_syguid` varchar(50), 
  `yw_kck_stopsalereason` varchar(200), 
  `yw_kck_xq` double, 
  `yw_kck_iskeeppricebreed` double, 
  `yw_kck_isagreementbreed` double, 
  `yw_kck_isvaluablebreed` double, 
  `yw_kck_basematerielguideprice` double, 
  `yw_kck_ispricesetbyfactory` double, 
  `yw_kck_propricemakedate` date, 
  `yw_kck_countrylimitpriceadjustdate` date, 
  `yw_kck_hyzk` double, 
  `yw_kck_requireclass` varchar(200), 
  `yw_kck_essentialdruglist` varchar(200), 
  `yw_kck_materiellong` double, 
  `yw_kck_materielwidth` double, 
  `yw_kck_materielhigh` double, 
  `yw_kck_storesrequireclass` varchar(200), 
  `yw_kck_subdirct` double, 
  `yw_kck_ldw` varchar(30), 
  `yw_kck_issalepromotion` double, 
  `yw_kck_isfood` double, 
  `yw_kck_c_xs` double, 
  `yw_kck_cfflsx` varchar(50), 
  `yw_kck_wxsy_lb` varchar(50), 
  `yw_kck_wxsy_imgurl` varchar(200), 
  `yw_kck_ischeckmedidevices` double, 
  `yw_kck_iswholepick` double, 
  `yw_kck_c_pasplb` varchar(50), 
  `yw_kck_splitratio` double, 
  `yw_kck_cfhjlsj` double, 
  `yw_kck_zlfl` varchar(50), 
  `yw_kck_zdyhqxrq` date, 
  `yw_kck_zl` double, 
  `yw_kck_pzwhqsxq` date, 
  `yw_kck_wmslb` varchar(50), 
  `yw_kck_bmfl` varchar(50), 
  `yw_kck_wmshl` varchar(50), 
  `yw_kck_sfyyp` double, 
  `yw_kck_sfyxp` double, 
  `yw_kck_sfxyzp` double, 
  `yw_kck_sfyyy` double, 
  `yw_kck_mdyhsx` double, 
  `yw_kck_light` varchar(20), 
  `organization_guid` varchar(50), 
  `organization_code` varchar(50), 
  `organization_name` varchar(50), 
  `organization_helpcode` varchar(50), 
  `organization_fullname` varchar(500), 
  `organization_notes` varchar(100), 
  `organization_parentguid` varchar(50), 
  `organization_isleaf` double, 
  `organization_englishname` varchar(100), 
  `organization_othername` varchar(100), 
  `organization_organizationtypeguid` varchar(50), 
  `organization_financecode` varchar(50), 
  `organization_chtname` varchar(50), 
  `organization_fullcode` varchar(50), 
  `organization_accountconnstring` varchar(500), 
  `organization_isforbidden` double, 
  `organization_forbiddendate` date, 
  `organization_forbiddenguid` varchar(50), 
  `organization_organizationtaxrate` double, 
  `organization_issenderorganization` double, 
  `organization_isdetail` double, 
  `organization_subsellpricetype` varchar(50), 
  `organization_opendate` date, 
  `organization_fstartyear` varchar(50), 
  `organization_fstartperiod` varchar(50), 
  `organization_fcurryear` varchar(50), 
  `organization_fcurrperiod` varchar(50), 
  `organization_isauditing` double, 
  `organization_auditingdate` date, 
  `organization_auditingguid` varchar(50), 
  `organization_accountdate` date, 
  `organization_accounttime` varchar(50), 
  `organization_lastaccountdate` date, 
  `organization_isaccount` double, 
  `organization_subtype` varchar(50), 
  `organization_subrange` varchar(100), 
  `organization_subscale` varchar(50), 
  `organization_competestatustype` varchar(50), 
  `organization_sellpricestatustype` varchar(50), 
  `organization_medinsuranceanalysetype` varchar(50), 
  `organization_addr` varchar(200), 
  `organization_subdescribe` varchar(200), 
  `organization_storemanagername` varchar(50), 
  `organization_storemanagerbirth` date, 
  `organization_tel` varchar(20), 
  `organization_storemanagerinauguralday` date, 
  `organization_ishaspiece` double, 
  `organization_workage` double, 
  `organization_iscitymedinsurance` double, 
  `organization_isprovincemedinsurance` double, 
  `organization_israilwaymedinsurance` double, 
  `organization_enterpriseage` double, 
  `organization_ischronicmedinsurance` double, 
  `organization_isspecialmedinsurance` double, 
  `organization_plandailysaleamount` double, 
  `organization_plandailygrossamount` double, 
  `organization_preservedailygrossamount` double, 
  `organization_yearsaletargetamount` double, 
  `organization_yeargrosstargetamount` double, 
  `organization_yeargrossratetarget` double, 
  `organization_stockmonthlytarget` double, 
  `organization_yearfeetarget` double, 
  `organization_subskucheckquantity` double, 
  `organization_personnelorgcount` double, 
  `organization_actualmancount` double, 
  `organization_saleclerkcount` double, 
  `organization_salepromotercount` double, 
  `organization_leasesigndate` date, 
  `organization_leasematuritydate` date, 
  `organization_buildarea` double, 
  `organization_businessarea` double, 
  `organization_areauserate` double, 
  `organization_storerent` double, 
  `organization_dailyrent` double, 
  `organization_yeartotalrent` double, 
  `organization_yearbusinessrent` double, 
  `organization_pxdevoteaim` double, 
  `organization_yearsaleperheadaim` double, 
  `organization_saleclerkperaim` double, 
  `organization_summary` varchar(200), 
  `organization_subcommisstype` varchar(50), 
  `organization_isfranchise` double, 
  `organization_isdirectnoaddprice` double, 
  `organization_paystylegroup` varchar(400), 
  `organization_printno` varchar(10), 
  `organization_orgtype` varchar(50), 
  `organization_id` double, 
  `organization_checkstocksubbh` varchar(2000), 
  `organization_foperationcheck` double, 
  `organization_lat` double, 
  `organization_lng` double, 
  `organization_wx_id` varchar(50), 
  `organization_token` varchar(50), 
  `organization_functionname` varchar(50), 
  `organization_openid` varchar(50), 
  `organization_cloudplatcode` varchar(50), 
  `organization_cloudentcode` varchar(100), 
  `organization_cloudentkey` varchar(100), 
  `organization_branchaccountinfo` varchar(500), 
  `organization_issy` varchar(2), 
  `organization_ismeituan` double, 
  `organization_isteldelivery` double, 
  `organization_isyb` double, 
  `organization_zys` varchar(50), 
  `organization_xys` varchar(50), 
  `organization_pianqu` varchar(30), 
  `organization_cwdl` varchar(200), 
  `organization2_guid` varchar(50), 
  `organization2_code` varchar(50), 
  `organization2_name` varchar(50), 
  `organization2_helpcode` varchar(50), 
  `organization2_fullname` varchar(500), 
  `organization2_notes` varchar(100), 
  `organization2_parentguid` varchar(50), 
  `organization2_isleaf` double, 
  `organization2_englishname` varchar(100), 
  `organization2_othername` varchar(100), 
  `organization2_organization2typeguid` varchar(50), 
  `organization2_financecode` varchar(50), 
  `organization2_chtname` varchar(50), 
  `organization2_fullcode` varchar(50), 
  `organization2_accountconnstring` varchar(500), 
  `organization2_isforbidden` double, 
  `organization2_forbiddendate` date, 
  `organization2_forbiddenguid` varchar(50), 
  `organization2_organization2taxrate` double, 
  `organization2_issenderorganization2` double, 
  `organization2_isdetail` double, 
  `organization2_subsellpricetype` varchar(50), 
  `organization2_opendate` date, 
  `organization2_fstartyear` varchar(50), 
  `organization2_fstartperiod` varchar(50), 
  `organization2_fcurryear` varchar(50), 
  `organization2_fcurrperiod` varchar(50), 
  `organization2_isauditing` double, 
  `organization2_auditingdate` date, 
  `organization2_auditingguid` varchar(50), 
  `organization2_accountdate` date, 
  `organization2_accounttime` varchar(50), 
  `organization2_lastaccountdate` date, 
  `organization2_isaccount` double, 
  `organization2_subtype` varchar(50), 
  `organization2_subrange` varchar(100), 
  `organization2_subscale` varchar(50), 
  `organization2_competestatustype` varchar(50), 
  `organization2_sellpricestatustype` varchar(50), 
  `organization2_medinsuranceanalysetype` varchar(50), 
  `organization2_addr` varchar(200), 
  `organization2_subdescribe` varchar(200), 
  `organization2_storemanagername` varchar(50), 
  `organization2_storemanagerbirth` date, 
  `organization2_tel` varchar(20), 
  `organization2_storemanagerinauguralday` date, 
  `organization2_ishaspiece` double, 
  `organization2_workage` double, 
  `organization2_iscitymedinsurance` double, 
  `organization2_isprovincemedinsurance` double, 
  `organization2_israilwaymedinsurance` double, 
  `organization2_enterpriseage` double, 
  `organization2_ischronicmedinsurance` double, 
  `organization2_isspecialmedinsurance` double, 
  `organization2_plandailysaleamount` double, 
  `organization2_plandailygrossamount` double, 
  `organization2_preservedailygrossamount` double, 
  `organization2_yearsaletargetamount` double, 
  `organization2_yeargrosstargetamount` double, 
  `organization2_yeargrossratetarget` double, 
  `organization2_stockmonthlytarget` double, 
  `organization2_yearfeetarget` double, 
  `organization2_subskucheckquantity` double, 
  `organization2_personnelorgcount` double, 
  `organization2_actualmancount` double, 
  `organization2_saleclerkcount` double, 
  `organization2_salepromotercount` double, 
  `organization2_leasesigndate` date, 
  `organization2_leasematuritydate` date, 
  `organization2_buildarea` double, 
  `organization2_businessarea` double, 
  `organization2_areauserate` double, 
  `organization2_storerent` double, 
  `organization2_dailyrent` double, 
  `organization2_yeartotalrent` double, 
  `organization2_yearbusinessrent` double, 
  `organization2_pxdevoteaim` double, 
  `organization2_yearsaleperheadaim` double, 
  `organization2_saleclerkperaim` double, 
  `organization2_summary` varchar(200), 
  `organization2_subcommisstype` varchar(50), 
  `organization2_isfranchise` double, 
  `organization2_isdirectnoaddprice` double, 
  `organization2_paystylegroup` varchar(400), 
  `organization2_printno` varchar(10), 
  `organization2_orgtype` varchar(50), 
  `organization2_id` double, 
  `organization2_checkstocksubbh` varchar(2000), 
  `organization2_foperationcheck` double, 
  `organization2_lat` double, 
  `organization2_lng` double, 
  `organization2_wx_id` varchar(50), 
  `organization2_token` varchar(50), 
  `organization2_functionname` varchar(50), 
  `organization2_openid` varchar(50), 
  `organization2_cloudplatcode` varchar(50), 
  `organization2_cloudentcode` varchar(100), 
  `organization2_cloudentkey` varchar(100), 
  `organization2_branchaccountinfo` varchar(500), 
  `organization2_issy` varchar(2), 
  `organization2_ismeituan` double, 
  `organization2_isteldelivery` double, 
  `organization2_isyb` double, 
  `organization2_zys` varchar(50), 
  `organization2_xys` varchar(50), 
  `organization2_pianqu` varchar(30), 
  `organization2_cwdl` varchar(200), 
  `gl_ryk_zm` varchar(30), 
  `gl_ryk_dh` varchar(30), 
  `gl_ryk_xm` varchar(80), 
  `gl_ryk_jb` double, 
  `gl_ryk_jhed` double, 
  `gl_ryk_zdf` double, 
  `gl_ryk_clf` double, 
  `gl_ryk_gz` double, 
  `gl_ryk_jj` double, 
  `gl_ryk_qtfy` double, 
  `gl_ryk_lxfy` double, 
  `gl_ryk_ll1` double, 
  `gl_ryk_ll2` double, 
  `gl_ryk_ll3` double, 
  `gl_ryk_tig` double, 
  `gl_ryk_bz` varchar(100), 
  `gl_ryk_max_je` double, 
  `gl_ryk_tcbz` varchar(200), 
  `gl_ryk_zkxx` double, 
  `gl_ryk_ryid` varchar(30), 
  `gl_ryk_zdxj` varchar(30), 
  `gl_ryk_km1` varchar(30), 
  `gl_ryk_km2` varchar(30), 
  `gl_ryk_km3` varchar(30), 
  `gl_ryk_km4` varchar(500), 
  `gl_ryk_km5` varchar(30), 
  `gl_ryk_fisgmp` double, 
  `gl_ryk_jgfa` double, 
  `gl_ryk_guid` varchar(50), 
  `gl_ryk_branchguid` varchar(50), 
  `gl_ryk_operatortype` varchar(50), 
  `gl_ryk_termcontroltype` varchar(100), 
  `gl_ryk_yf_xs_1` double, 
  `gl_ryk_beginamount` double, 
  `gl_ryk_debitamount` double, 
  `gl_ryk_creditamount` double, 
  `gl_ryk_endamount` double, 
  `gl_ryk_beginpreamount` double, 
  `gl_ryk_preamount` double, 
  `gl_ryk_paybeginamount` double, 
  `gl_ryk_paydebitamount` double, 
  `gl_ryk_paycreditamount` double, 
  `gl_ryk_payendamount` double, 
  `gl_ryk_paybeginpreamount` double, 
  `gl_ryk_paypreamount` double, 
  `gl_ryk_attribute` varchar(50), 
  `gl_ryk_employeecompany` varchar(50), 
  `gl_ryk_isauthtwoclassmentaldrug` double, 
  `gl_ryk_isauthminddrug` double, 
  `gl_ryk_isauthanaesthetic` double, 
  `gl_ryk_isauthmedicaltoxicity` double, 
  `gl_ryk_isauthradioactive` double, 
  `gl_ryk_isauthisvaccine` double, 
  `gl_ryk_isauthdangerchemistry` double, 
  `gl_ryk_isauthdiagnosticreagent` double, 
  `gl_ryk_isauthstimulant` double, 
  `gl_ryk_isauthephedrine` double, 
  `gl_ryk_isautheggpreparation` double, 
  `gl_ryk_isauthtlhormone` double, 
  `gl_ryk_isauthmedicaldevicestype` double, 
  `gl_ryk_tel` varchar(30), 
  `gl_ryk_position` varchar(50), 
  `gl_ryk_positiondesc` varchar(100), 
  `gl_ryk_idcode` varchar(50), 
  `gl_ryk_mobilephone` varchar(20), 
  `gl_ryk_nationalcode` varchar(20), 
  `gl_ryk_provincecode` varchar(20), 
  `gl_ryk_citycode` varchar(20), 
  `gl_ryk_addr` varchar(200), 
  `gl_ryk_netcode` varchar(20), 
  `gl_ryk_email` varchar(50), 
  `gl_ryk_ismessagereceive` double, 
  `gl_ryk_ismarried` double, 
  `gl_ryk_sex` varchar(10), 
  `gl_ryk_birth` date, 
  `gl_ryk_age` double, 
  `gl_ryk_edulevel` varchar(20), 
  `gl_ryk_bloodtype` varchar(20), 
  `gl_ryk_professtitle` varchar(50), 
  `gl_ryk_clerktype` varchar(50), 
  `gl_ryk_isforbidden` double, 
  `gl_ryk_forbiddenguid` varchar(50), 
  `gl_ryk_forbiddendate` date, 
  `gl_ryk_forbiddenreason` varchar(200), 
  `gl_ryk_joinworkdate` date, 
  `gl_ryk_graduateschool` varchar(50), 
  `gl_ryk_profession` varchar(200), 
  `gl_ryk_workstatus` varchar(50), 
  `gl_ryk_substockid` varchar(4000), 
  `gl_ryk_wmsisexport` double, 
  `gl_ryk_wmsexportdate` date, 
  `gl_ryk_wmsexportcount` double, 
  `newstoreset_parentguid` varchar(50), 
  `newstoreset_dwlb` double, 
  `newstoreset_tjbh` varchar(30), 
  `newstoreset_mc` varchar(80), 
  `newstoreset_zjm` varchar(30), 
  `newstoreset_yhzh` varchar(80), 
  `newstoreset_zzsh` varchar(80), 
  `newstoreset_fzr` varchar(80), 
  `newstoreset_tel` varchar(80), 
  `newstoreset_zxd` varchar(80), 
  `newstoreset_gdzb` varchar(80), 
  `newstoreset_tj_tag` varchar(80), 
  `newstoreset_kdrq` date, 
  `newstoreset_bz` varchar(100), 
  `newstoreset_zk` double, 
  `newstoreset_qyxz` varchar(80), 
  `newstoreset_frdb` varchar(80), 
  `newstoreset_info_fzr` varchar(80), 
  `newstoreset_xsr` varchar(80), 
  `newstoreset_creditterm` double, 
  `newstoreset_pzbh` varchar(80), 
  `newstoreset_dwlx` varchar(30), 
  `newstoreset_dwid` varchar(30), 
  `newstoreset_khh` varchar(80), 
  `newstoreset_yyzz` varchar(80), 
  `newstoreset_zzqx` date, 
  `newstoreset_txzh` varchar(100), 
  `newstoreset_email` varchar(80), 
  `newstoreset_edbz` double, 
  `newstoreset_edje` double, 
  `newstoreset_csbz` double, 
  `newstoreset_bz1` varchar(100), 
  `newstoreset_bz2` varchar(100), 
  `newstoreset_bz3` varchar(100), 
  `newstoreset_bz4` varchar(2000), 
  `newstoreset_bz5` varchar(100), 
  `newstoreset_yszkid` varchar(30), 
  `newstoreset_yszkkm` varchar(30), 
  `newstoreset_km1` varchar(30), 
  `newstoreset_km2` varchar(30), 
  `newstoreset_km3` varchar(30), 
  `newstoreset_km4` varchar(30), 
  `newstoreset_km5` varchar(30), 
  `newstoreset_fpath` varchar(80), 
  `newstoreset_fftppath` varchar(80), 
  `newstoreset_fpopserver` varchar(30), 
  `newstoreset_fpopport` double, 
  `newstoreset_fpopuser` varchar(30), 
  `newstoreset_fpoppass` varchar(30), 
  `newstoreset_fisgmp` double, 
  `newstoreset_jgfa` varchar(50), 
  `newstoreset_guid` varchar(50), 
  `newstoreset_createdate` date, 
  `newstoreset_updatedate` date, 
  `newstoreset_c_down_tag` double, 
  `newstoreset_fdeleted` double, 
  `newstoreset_stopsell` double, 
  `newstoreset_inoutstatus` double, 
  `newstoreset_branchguid` varchar(50), 
  `newstoreset_salechannel` varchar(800), 
  `newstoreset_txzhyxq` date, 
  `newstoreset_gspgmpyxq` date, 
  `newstoreset_flsx` varchar(50), 
  `newstoreset_mrjsfs` varchar(50), 
  `newstoreset_mrxsfs` varchar(50), 
  `newstoreset_shdz` varchar(100), 
  `newstoreset_fpdw` varchar(50), 
  `newstoreset_xxdz` varchar(200), 
  `newstoreset_yzbm` varchar(50), 
  `newstoreset_lxr` varchar(50), 
  `newstoreset_handtel` varchar(50), 
  `newstoreset_faxtel` varchar(50), 
  `newstoreset_xykzbz` double, 
  `newstoreset_khbz` double, 
  `newstoreset_zzjgdmzh` varchar(50), 
  `newstoreset_swdjz` varchar(50), 
  `newstoreset_gmpgspzsh` varchar(50), 
  `newstoreset_gmpgspyxq` date, 
  `newstoreset_fzrq` date, 
  `newstoreset_fzjg` varchar(50), 
  `newstoreset_zgbm` varchar(50), 
  `newstoreset_jjxz` varchar(50), 
  `newstoreset_zczb` varchar(50), 
  `newstoreset_jyfs` varchar(50), 
  `newstoreset_yydz` varchar(50), 
  `newstoreset_kcrq` date, 
  `newstoreset_kcjl` varchar(50), 
  `newstoreset_kcr` varchar(50), 
  `newstoreset_qyfzr` varchar(50), 
  `newstoreset_zlfzr` varchar(50), 
  `newstoreset_khywy` varchar(50), 
  `newstoreset_sqwtqsrq` date, 
  `newstoreset_sqwtjsrq` date, 
  `newstoreset_fzxx1` varchar(50), 
  `newstoreset_fzxx2` varchar(50), 
  `newstoreset_fzxx3` varchar(50), 
  `newstoreset_c_sfhg` double, 
  `newstoreset_operatorguid` varchar(50), 
  `newstoreset_bz6` date, 
  `newstoreset_ywyidentity` varchar(50), 
  `newstoreset_zlzk` varchar(200), 
  `newstoreset_dw_id` varchar(50), 
  `newstoreset_taglb` varchar(50), 
  `newstoreset_gp_nsxz` varchar(50), 
  `newstoreset_gp_xsya` varchar(50), 
  `newstoreset_gp_xsyb` varchar(50), 
  `newstoreset_gp_xsyc` varchar(50), 
  `newstoreset_khsctgbz` double, 
  `newstoreset_khfplx` varchar(50), 
  `newstoreset_wsxkzh` varchar(50), 
  `newstoreset_wsxkzxq` date, 
  `newstoreset_wxhxpxkzh` varchar(50), 
  `newstoreset_wxhxpxkxq` date, 
  `newstoreset_yljgxkzh` varchar(50), 
  `newstoreset_yljgxkqx` date, 
  `newstoreset_ylqxxkzh` varchar(50), 
  `newstoreset_ylqxxkqx` date, 
  `newstoreset_yslx` varchar(50), 
  `newstoreset_headcustomerguid` varchar(50), 
  `newstoreset_zzjgdmzqx` date, 
  `newstoreset_swdjzqx` date, 
  `newstoreset_zlbzxyh` varchar(100), 
  `newstoreset_zlbzxyqx` date, 
  `newstoreset_termcontroltype` varchar(100), 
  `newstoreset_arearange` varchar(50), 
  `newstoreset_checkcostprice` varchar(50), 
  `newstoreset_medicalinstrumenttype` varchar(50), 
  `newstoreset_twoclassmentaldrugemploy` varchar(50), 
  `newstoreset_mentaldrugauthoritybegindate` date, 
  `newstoreset_mentaldrugauthorityenddate` date, 
  `newstoreset_ephedrineempoly` varchar(50), 
  `newstoreset_ephedrinebegindate` date, 
  `newstoreset_ephedrineenddate` date, 
  `newstoreset_dbjtlhormoneemploy` varchar(50), 
  `newstoreset_dbjtlhormonebegindate` date, 
  `newstoreset_dbjtlhormoneenddate` date, 
  `newstoreset_paytaxestype` varchar(1), 
  `newstoreset_tdtype` varchar(100), 
  `newstoreset_pricetype` varchar(50), 
  `newstoreset_producelimit` double, 
  `newstoreset_periodcontrol` double, 
  `newstoreset_selldigit` double, 
  `newstoreset_invoiceamount` double, 
  `newstoreset_beginamount` double, 
  `newstoreset_debitamount` double, 
  `newstoreset_creditamount` double, 
  `newstoreset_endamount` double, 
  `newstoreset_beginpreamount` double, 
  `newstoreset_preamount` double, 
  `newstoreset_autocode` varchar(50), 
  `newstoreset_groupascriptioncode` varchar(50), 
  `newstoreset_attribute1` varchar(50), 
  `newstoreset_attribute2` varchar(50), 
  `newstoreset_attribute3` varchar(50), 
  `newstoreset_controltype` varchar(100), 
  `newstoreset_addr` varchar(100), 
  `newstoreset_isgroupenterprise` double, 
  `newstoreset_c_hkrq` double, 
  `newstoreset_c_jzrq` double, 
  `newstoreset_balanceday` double, 
  `newstoreset_backday` double, 
  `newstoreset_promotiontype` varchar(50), 
  `newstoreset_noteprintguid` varchar(50), 
  `newstoreset_printtag` varchar(2), 
  `newstoreset_noteprintguid2` varchar(50), 
  `newstoreset_opendate` date, 
  `newstoreset_sellpricetype` varchar(50), 
  `newstoreset_defaultdeliverorg` varchar(50), 
  `newstoreset_deliverer` varchar(50), 
  `newstoreset_deliverweek` varchar(50), 
  `newstoreset_pickoutstockid` varchar(500), 
  `newstoreset_sendline` varchar(50), 
  `newstoreset_pickoutorder` varchar(50), 
  `newstoreset_issplitmidpack` double, 
  `newstoreset_xqdaynumber` double, 
  `newstoreset_isconfiguredegree` double, 
  `newstoreset_autorecordwantgoods` double, 
  `newstoreset_subtype` varchar(50), 
  `newstoreset_subrange` varchar(50), 
  `newstoreset_subskucheckquantity` double, 
  `newstoreset_substockration` double, 
  `newstoreset_isauditing` double, 
  `newstoreset_auditingdate` date, 
  `newstoreset_auditingguid` varchar(50), 
  `newstoreset_organizationtaxrate` double, 
  `newstoreset_sendaddress` varchar(100), 
  `newstoreset_iscreatesubdept` double, 
  `newstoreset_subdeptid` varchar(50), 
  `newstoreset_subdeptname` varchar(50), 
  `newstoreset_subdepthelpcode` varchar(50), 
  `newstoreset_substockid` varchar(50), 
  `newstoreset_substockname` varchar(50), 
  `newstoreset_substockhelpcode` varchar(50), 
  `newstoreset_isjoininstore` double, 
  `newstoreset_issumbalancecus` double, 
  `newstoreset_shortforcustom` varchar(100), 
  `newstoreset_fcurryear` varchar(10), 
  `newstoreset_fcurrperiod` varchar(10), 
  `newstoreset_healthcertificate` varchar(100), 
  `newstoreset_healthfoodslimit` date, 
  `newstoreset_gspcontroltype` varchar(100), 
  `newstoreset_checkstocksubbh` varchar(2000), 
  `newstoreset_minday` double, 
  `newstoreset_maxday` double, 
  `newstoreset_zys` varchar(50), 
  `newstoreset_xys` varchar(50), 
  `substoretasksetdetail_guid` varchar(50), 
  `substoretasksetdetail_substoretasksetguid` varchar(50), 
  `substoretasksetdetail_year` varchar(10), 
  `substoretasksetdetail_month` varchar(10), 
  `substoretasksetdetail_storemancount` double, 
  `substoretasksetdetail_storestaffcount` double, 
  `substoretasksetdetail_grossprofittarget` double, 
  `substoretasksetdetail_saletarget` double, 
  `substoretasksetdetail_grossratetarget` double, 
  `substoretasksetdetail_stockdaytarget` double, 
  `substoretasksetdetail_stockamounttarget` double, 
  `substoretasksetdetail_monthstart` date, 
  `substoretasksetdetail_monthend` date, 
  `substoretasksetdetail_notes` varchar(50), 
  `substoretasksetdetail_monthsale` double, 
  `substoretasksetdetail_monthgrossprofit` double, 
  `substoretasksetdetail_monthgrossrate` double, 
  `substoretasksetdetail_monthstockamount` double, 
  `substoretasksetdetail_monthsourcegrossprofit` double, 
  `substoretasksetdetail_monthsourcegrossrate` double, 
  `substoretasksetdetail_monthvipsale` double, 
  `substoretasksetdetail_montcutomcount` double, 
  `substoretasksetdetail_montcutomprcice` double, 
  `substoretasksetdetail_montcutomskuprcice` double, 
  `substoretasksetdetail_montcutomsku` double, 
  `substoretasksetdetail_montcutomunitprcice` double, 
  `substoretasksetdetail_subbh` varchar(50), 
  `dim_member_id` varchar(30), 
  `dim_member_name` varchar(100), 
  `dim_member_fdate` date, 
  `dim_member_fxb` double, 
  `dim_member_fyear` double, 
  `dim_member_faddr` varchar(100), 
  `dim_member_addr` varchar(100), 
  `dim_member_tele` varchar(80), 
  `dim_member_lx` varchar(80), 
  `dim_member_fjksj` date, 
  `dim_member_fywsj` date, 
  `dim_member_bz` varchar(100), 
  `dim_member_je` double, 
  `dim_member_fdeleted` double, 
  `dim_member_ljje` double, 
  `dim_member_fforbid` double, 
  `dim_member_fcardtype` double, 
  `dim_member_frebate` varchar(50), 
  `dim_member_freserve` double, 
  `dim_member_ftime` double, 
  `dim_member_fidentityno` varchar(30), 
  `dim_member_ffamilytele` varchar(30), 
  `dim_member_fhelpcode` varchar(50), 
  `dim_member_jgfa` double, 
  `dim_member_createdate` date, 
  `dim_member_updatedate` date, 
  `dim_member_groupcode` varchar(80), 
  `dim_member_ljfs` double, 
  `dim_member_abatedate` date, 
  `dim_member_addupmoney` double, 
  `dim_member_sumaddupmoney` double, 
  `dim_member_jfje` double, 
  `dim_member_localaddup` double, 
  `dim_member_groupaddup` double, 
  `dim_member_localcachin` double, 
  `dim_member_groupcachin` double, 
  `dim_member_localintegral` double, 
  `dim_member_groupintegral` double, 
  `dim_member_guid` varchar(50), 
  `dim_member_localintegralcachin` double, 
  `dim_member_groupintegralcachin` double, 
  `dim_member_localintegralcach` double, 
  `dim_member_groupintegralcach` double, 
  `dim_member_branchguid` varchar(50), 
  `dim_member_xb` varchar(50), 
  `dim_member_localupdated` date, 
  `dim_member_beginconsumeamount` double, 
  `dim_member_beginconsumeintegral` double, 
  `dim_member_reservecard` varchar(100), 
  `dim_member_phonenumber` varchar(50), 
  `dim_member_postalcode` varchar(50), 
  `dim_member_e_mail` varchar(100), 
  `dim_member_netcode` varchar(100), 
  `dim_member_degree` varchar(100), 
  `dim_member_vocation` varchar(100), 
  `dim_member_registersuborgan` varchar(100), 
  `dim_member_servicesperson` varchar(100), 
  `dim_member_memberarea` varchar(100), 
  `dim_member_birthdayawoketag` double, 
  `dim_member_defaultnotecontent` varchar(500), 
  `dim_member_latelycaredate` date, 
  `dim_member_latelycashindate` date, 
  `dim_member_latelyconsumedate` date, 
  `dim_member_caretype` varchar(100), 
  `dim_member_personellike` varchar(100), 
  `dim_member_memberrememberday` date, 
  `dim_member_rememberawoketag` double, 
  `dim_member_rememberdescription` varchar(1000), 
  `dim_member_memberawokeday` date, 
  `dim_member_awokedayawoketag` double, 
  `dim_member_awokedescription` varchar(1000), 
  `dim_member_ismarried` double, 
  `dim_member_operatorguid` varchar(50), 
  `dim_member_hypass` varchar(50), 
  `dim_member_integralmultiple` varchar(50), 
  `dim_member_registersuborganname` varchar(80), 
  `dim_member_factoryno` varchar(50), 
  `dim_member_bloodtype` varchar(50), 
  `dim_member_age` double, 
  `dim_member_culturedegree` varchar(50), 
  `dim_member_job` varchar(50), 
  `dim_member_familymember1` varchar(50), 
  `dim_member_relationship1` varchar(50), 
  `dim_member_healthdemand1` varchar(50), 
  `dim_member_familymember2` varchar(50), 
  `dim_member_relationship2` varchar(50), 
  `dim_member_healthdemand2` varchar(50), 
  `dim_member_anamnesis` varchar(500), 
  `dim_member_otherthings` varchar(100), 
  `dim_member_irritabilityhistory` varchar(100), 
  `dim_member_oftenmateriel` varchar(100), 
  `dim_member_healthactivity` varchar(100), 
  `dim_member_clubtype` varchar(50), 
  `dim_member_isnoteawoke` double, 
  `dim_member_clearintegraldate` date, 
  `dim_member_ispubliccard` double, 
  `dim_member_mnxtillness` varchar(100), 
  `dim_member_gjjbillness` varchar(100), 
  `dim_member_xhxtillness` varchar(100), 
  `dim_member_hxxtillness` varchar(100), 
  `dim_member_fkjbillness` varchar(100), 
  `dim_member_xnxgillness` varchar(100), 
  `dim_member_tnbillness` varchar(100), 
  `dim_member_eatmaterielnono` varchar(100), 
  `dim_member_isforlornman` double, 
  `dim_member_transactor` varchar(50), 
  `dim_member_groupcach` double, 
  `dim_member_bakfrebate` varchar(50), 
  `dim_member_nationnalitycode` varchar(50), 
  `dim_member_provincecode` varchar(50), 
  `dim_member_citycode` varchar(50), 
  `dim_member_ismedicare` double, 
  `dim_member_nointegral` double, 
  `dim_member_cedulatype` varchar(50), 
  `dim_member_factorytime` date, 
  `dim_member_factorydate` date, 
  `dim_member_alteroperatorguid` varchar(50), 
  `dim_member_distance` double, 
  `dim_member_memberlable` varchar(200), 
  `dim_member_isnetcard` double, 
  `dim_member_netnumber` varchar(50), 
  `dim_member_ybid` varchar(50), 
  `dim_member_yblx` varchar(50), 
  `dim_member_zq` double, 
  `dim_member_age_from_fdate` bigint, 
  `dim_member_age_class` int, 
  `item1_guid` varchar(50), 
  `item1_dataitemtypeguid` varchar(50), 
  `item1_code` varchar(50), 
  `item1_name` varchar(100), 
  `item1_helpcode` varchar(100), 
  `item1_fullname` varchar(500), 
  `item1_parentguid` varchar(50), 
  `item1_isleaf` double, 
  `item1_char1` varchar(100), 
  `item1_char2` varchar(100), 
  `item1_char3` varchar(100), 
  `item1_char4` varchar(100), 
  `item1_char5` varchar(100), 
  `item1_float1` double, 
  `item1_float2` double, 
  `item1_float3` double, 
  `item1_float4` double, 
  `item1_float5` double, 
  `item1_chtname` varchar(100), 
  `item1_englishname` varchar(100), 
  `item1_issystem` double, 
  `item1_notes` varchar(100), 
  `item1_branchguid` varchar(50), 
  `item1_isforbidden` double, 
  `item1_iscostinvolved` double, 
  `item1_billtype` varchar(50), 
  `item2_guid` varchar(50), 
  `item2_dataitemtypeguid` varchar(50), 
  `item2_code` varchar(50), 
  `item2_name` varchar(100), 
  `item2_helpcode` varchar(100), 
  `item2_fullname` varchar(500), 
  `item2_parentguid` varchar(50), 
  `item2_isleaf` double, 
  `item2_char1` varchar(100), 
  `item2_char2` varchar(100), 
  `item2_char3` varchar(100), 
  `item2_char4` varchar(100), 
  `item2_char5` varchar(100), 
  `item2_float1` double, 
  `item2_float2` double, 
  `item2_float3` double, 
  `item2_float4` double, 
  `item2_float5` double, 
  `item2_chtname` varchar(100), 
  `item2_englishname` varchar(100), 
  `item2_issystem` double, 
  `item2_notes` varchar(100), 
  `item2_branchguid` varchar(50), 
  `item2_isforbidden` double, 
  `item2_iscostinvolved` double, 
  `item2_billtype` varchar(50), 
  `item3_guid` varchar(50), 
  `item3_dataitemtypeguid` varchar(50), 
  `item3_code` varchar(50), 
  `item3_name` varchar(100), 
  `item3_helpcode` varchar(100), 
  `item3_fullname` varchar(500), 
  `item3_parentguid` varchar(50), 
  `item3_isleaf` double, 
  `item3_char1` varchar(100), 
  `item3_char2` varchar(100), 
  `item3_char3` varchar(100), 
  `item3_char4` varchar(100), 
  `item3_char5` varchar(100), 
  `item3_float1` double, 
  `item3_float2` double, 
  `item3_float3` double, 
  `item3_float4` double, 
  `item3_float5` double, 
  `item3_chtname` varchar(100), 
  `item3_englishname` varchar(100), 
  `item3_issystem` double, 
  `item3_notes` varchar(100), 
  `item3_branchguid` varchar(50), 
  `item3_isforbidden` double, 
  `item3_iscostinvolved` double, 
  `item3_billtype` varchar(50), 
  `kdrq_datatime` date , 
  `kdrq_date_time` timestamp , 
  `kdrq_date_id` varchar(8) , 
  `kdrq_date_no` varchar(10) , 
  `kdrq_date_desc` varchar(50) , 
  `kdrq_day_of_week` int , 
  `kdrq_day_of_week_desc` varchar(10) , 
  `kdrq_day_of_month` int , 
  `kdrq_day_of_year` int , 
  `kdrq_week_id` varchar(10) , 
  `kdrq_week_desc` varchar(20) , 
  `kdrq_week_of_month` int , 
  `kdrq_week_of_year` int , 
  `kdrq_first_day_of_week` date , 
  `kdrq_first_day_of_week_short` varchar(10) , 
  `kdrq_month_id` varchar(20) , 
  `kdrq_month_no` varchar(20) , 
  `kdrq_month_of_year` int , 
  `kdrq_month_desc` varchar(20) , 
  `kdrq_month_long_desc` varchar(50) , 
  `kdrq_first_day_of_month` date , 
  `kdrq_quarter_id` varchar(20) , 
  `kdrq_quarter_of_year` int , 
  `kdrq_quarter_desc` varchar(20) , 
  `kdrq_quarter_long_desc` varchar(20) , 
  `kdrq_year_id` varchar(4) , 
  `kdrq_year_desc` varchar(10) , 
  `kdrq_first_day_of_year` date 
)
PARTITIONED BY ( 
  `dt` string)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( 
  "separatorChar"="|" 
  ) 
STORED AS TEXTFILE;

INSERT OVERWRITE TABLE pharmacy.wide_pharmacy_sales_2019_druid PARTITION(dt='20200106')
SELECT 
    subfhd_fid,
    subfhd_fyear,
    subfhd_djlx,
    subfhd_fperiod,
    subfhd_ftype,
    subfhd_jzbz,
    subfhd_shbz,
    subfhd_lsh,
    subfhd_kdrq,
    subfhd_subbh,
    subfhd_dh,
    subfhd_lb,
    subfhd_hh,
    subfhd_zzsl,
    subfhd_sl,
    subfhd_zk,
    subfhd_dj,
    subfhd_lsj,
    subfhd_sj,
    subfhd_je,
    subfhd_se,
    subfhd_jshj,
    subfhd_cbj,
    subfhd_cbe,
    subfhd_ml,
    subfhd_lsze,
    subfhd_cj,
    subfhd_xsr,
    subfhd_bz,
    subfhd_czry,
    subfhd_ph1,
    subfhd_ph2,
    subfhd_ph3_sl,
    subfhd_ph1_xq,
    subfhd_fvchnum,
    subfhd_fgroup,
    subfhd_fvch,
    subfhd_stockid,
    subfhd_bm,
    subfhd_yhkh,
    subfhd_pcdh,
    subfhd_fpzdate,
    subfhd_fpzperiod,
    subfhd_fpzyear,
    subfhd_vchoperation,
    subfhd_fvchid,
    subfhd_jzry,
    subfhd_commissionrate,
    subfhd_scrq,
    subfhd_batchprice,
    subfhd_billtime,
    subfhd_jzrq,
    subfhd_balancebaseprice,
    subfhd_integralvalue,
    subfhd_posguid,
    subfhd_dealguid,
    subfhd_daliylogdate,
    subfhd_customerinfo,
    subfhd_zblastpurchaseprice,
    subfhd_zbjhdj,
    subfhd_headbatchnumber,
    subfhd_suppliercode,
    subfhd_cxfaid,
    subfhd_pfml,
    subfhd_hsml,
    subfhd_rightoptcode,
    subfhd_workshiftid,
    subfhd_tcfs,
    subfhd_cxfamxid,
    subfhd_kh,
    subfhd_policytype,
    subfhd_fsfcj,
    subfhd_cdbz,
    subfhd_personname,
    subfhd_idcardno,
    subfhd_boxid,
    subfhd_checknum,
    subfhd_isrecheck,
    subfhd_recheckdate,
    subfhd_recheckoperatorguid,
    subfhd_tjbh,
    subfhd_auditingname,
    subfhd_patientname,
    subfhd_doctorname,
    subfhd_doctorcode,
    subfhd_clname,
    subfhd_pharmacistname,
    subfhd_appdetailguid,
    subfhd_appguid,
    subfhd_c_ys,
    subfhd_c_cfh,
    subfhd_posname,
    subfhd_omsbz,
    yw_kck_lb,
    yw_kck_hh,
    yw_kck_pm,
    yw_kck_bm,
    yw_kck_cd,
    yw_kck_dwbh,
    yw_kck_dwmc,
    yw_kck_gg,
    yw_kck_pdw,
    yw_kck_yblb,
    yw_kck_mjl,
    yw_kck_mjzl,
    yw_kck_jj,
    yw_kck_jj_ckj,
    yw_kck_ckj,
    yw_kck_pfj,
    yw_kck_lsj,
    yw_kck_cbj,
    yw_kck_ycbj,
    yw_kck_lastbalanceprice,
    yw_kck_sjsl,
    yw_kck_xhsl,
    yw_kck_xh,
    yw_kck_jhsl,
    yw_kck_qtfcsl,
    yw_kck_qtsrsl,
    yw_kck_max_sl,
    yw_kck_min_sl,
    yw_kck_dy_tag,
    yw_kck_tj_tag,
    yw_kck_hs_tag,
    yw_kck_ckj_tag,
    yw_kck_zy,
    yw_kck_xq_date,
    yw_kck_jh_date,
    yw_kck_xh_date,
    yw_kck_pfj1,
    yw_kck_sj,
    yw_kck_ls_jj1,
    yw_kck_ls_jj2,
    yw_kck_ls_jj3,
    yw_kck_kh,
    yw_kck_zk,
    yw_kck_zzsl,
    yw_kck_pm_zjm,
    yw_kck_bz,
    yw_kck_hh_tmp,
    yw_kck_sjsl_ls,
    yw_kck_tcbl1,
    yw_kck_tcbl2,
    yw_kck_tcbl3,
    yw_kck_ph1,
    yw_kck_ph2,
    yw_kck_ph3,
    yw_kck_zyc_tag,
    yw_kck_zzrs_tag,
    yw_kck_ph3_sl,
    yw_kck_lsj1,
    yw_kck_bzsl,
    yw_kck_sj1,
    yw_kck_tm,
    yw_kck_pj,
    yw_kck_pdsl,
    yw_kck_sysl,
    yw_kck_sx,
    yw_kck_spid,
    yw_kck_sfcf,
    yw_kck_pzwh,
    yw_kck_scdw,
    yw_kck_scrq,
    yw_kck_zcsb,
    yw_kck_jjff,
    yw_kck_fdeleted,
    yw_kck_sx1,
    yw_kck_sx2,
    yw_kck_dwmc1,
    yw_kck_dwmc2,
    yw_kck_jx,
    yw_kck_ysbz,
    yw_kck_cctj,
    yw_kck_tybz,
    yw_kck_sybz,
    yw_kck_dls,
    yw_kck_bzgg,
    yw_kck_bz1,
    yw_kck_bz2,
    yw_kck_bz3,
    yw_kck_bz4,
    yw_kck_bz5,
    yw_kck_bzbz,
    yw_kck_bzhh,
    yw_kck_bzl,
    yw_kck_zbzl,
    yw_kck_kcspid,
    yw_kck_xssrid,
    yw_kck_xscbid,
    yw_kck_km1,
    yw_kck_km2,
    yw_kck_km3,
    yw_kck_km4,
    yw_kck_km5,
    yw_kck_fonlymoney,
    yw_kck_fisybpz,
    yw_kck_fisgmp,
    yw_kck_scrqrequest,
    yw_kck_yxqrequest,
    yw_kck_tcbl,
    yw_kck_fisrecipe,
    yw_kck_fsjbl,
    yw_kck_ftsbz,
    yw_kck_hyj,
    yw_kck_iscolorsize,
    yw_kck_noabate,
    yw_kck_c_gx,
    yw_kck_c_xz,
    yw_kck_c_yhly,
    yw_kck_c_zdyh,
    yw_kck_guid,
    yw_kck_createdate,
    yw_kck_updatedate,
    yw_kck_c_ypfl,
    yw_kck_stocktaxrate,
    yw_kck_materieldiscountrateid,
    yw_kck_gspsortid,
    yw_kck_materielimage,
    yw_kck_iscourtesycard,
    yw_kck_courtesycardtypeid,
    yw_kck_parvalue,
    yw_kck_issalespromotion,
    yw_kck_inoutstatus,
    yw_kck_branchguid,
    yw_kck_fdate,
    yw_kck_bh,
    yw_kck_ghqy,
    yw_kck_gmpzsh,
    yw_kck_gmprzrq,
    yw_kck_gmprzxq,
    yw_kck_ccjybgs,
    yw_kck_syjybgs,
    yw_kck_syjyjl,
    yw_kck_cgyy,
    yw_kck_cgy,
    yw_kck_yj_yw,
    yw_kck_jl_yw,
    yw_kck_rq_yw,
    yw_kck_yj_zg,
    yw_kck_jl_zg,
    yw_kck_rq_zg,
    yw_kck_yj_wj,
    yw_kck_jl_wj,
    yw_kck_rq_wj,
    yw_kck_yj_jl,
    yw_kck_ypqk,
    yw_kck_zyx1,
    yw_kck_zyx2,
    yw_kck_zyx3,
    yw_kck_zyx4,
    yw_kck_hgbz,
    yw_kck_spry,
    yw_kck_bqsms,
    yw_kck_wcbz,
    yw_kck_gjxj,
    yw_kck_ckjj,
    yw_kck_gys,
    yw_kck_gyslb,
    yw_kck_gysdb,
    yw_kck_sqwtqx,
    yw_kck_ckgl,
    yw_kck_gndls,
    yw_kck_jkzczh,
    yw_kck_jkka,
    yw_kck_xkzqx,
    yw_kck_yhcs,
    yw_kck_wjpw,
    yw_kck_ypbz,
    yw_kck_ysrkyxqbz,
    yw_kck_cmdjcbz,
    yw_kck_syystxbz,
    yw_kck_yszdbz,
    yw_kck_srysfhbz,
    yw_kck_bcyhyjfbz,
    yw_kck_xpzgzbz,
    yw_kck_xpzgzqx,
    yw_kck_lsjgllb,
    yw_kck_cgxj,
    yw_kck_cgjccgxjbz,
    yw_kck_xjsbz,
    yw_kck_rjksxbz,
    yw_kck_kcsx,
    yw_kck_kcxx,
    yw_kck_xjkxxbz,
    yw_kck_abcflsx,
    yw_kck_ztflsx,
    yw_kck_fzflsx1,
    yw_kck_fzflsx2,
    yw_kck_fzflsx3,
    yw_kck_fzflsx4,
    yw_kck_fzflsx5,
    yw_kck_isauditing,
    yw_kck_iscancel,
    yw_kck_lxtjbh,
    yw_kck_salechannel,
    yw_kck_salearea,
    yw_kck_operatorguid,
    yw_kck_auditingguid,
    yw_kck_djzt,
    yw_kck_vipintegraltype,
    yw_kck_isnebalance,
    yw_kck_auditingdate,
    yw_kck_jkpzbz,
    yw_kck_zybz,
    yw_kck_lspszbz_tag,
    yw_kck_largepackunit,
    yw_kck_largepackbarcode,
    yw_kck_middlepackunit,
    yw_kck_middlepackbarcode,
    yw_kck_balanceproperty,
    yw_kck_medicalinstrumenttype,
    yw_kck_iseggpreparation,
    yw_kck_istwoclassmentaldrug,
    yw_kck_isephedrine,
    yw_kck_istlhormone,
    yw_kck_isminddrug,
    yw_kck_isdangerchemistry,
    yw_kck_materialimage,
    yw_kck_groupcontrolpurtype,
    yw_kck_ispick,
    yw_kck_autocode,
    yw_kck_smallpackage,
    yw_kck_smallpackunit,
    yw_kck_smallpackagebarcode,
    yw_kck_isanaesthetic,
    yw_kck_ismedicaltoxicity,
    yw_kck_isvaccine,
    yw_kck_isdiagnosticreagent,
    yw_kck_isstimulant,
    yw_kck_shyb,
    yw_kck_syb,
    yw_kck_tlb,
    yw_kck_iscontrolsellscope,
    yw_kck_financetype,
    yw_kck_grouppurchbranchguid,
    yw_kck_purchasebalance,
    yw_kck_c_yongzi,
    yw_kck_stockid,
    yw_kck_ysry,
    yw_kck_ysywy,
    yw_kck_storeman,
    yw_kck_cd_zjm,
    yw_kck_isselectbatch,
    yw_kck_brandattribute,
    yw_kck_grossratetype,
    yw_kck_reservelistcode,
    yw_kck_historycode,
    yw_kck_salespromotiontypeid,
    yw_kck_wmsisexport,
    yw_kck_wmsrecordstatus,
    yw_kck_wmsexportcount,
    yw_kck_wmsexportdate,
    yw_kck_ismonitor,
    yw_kck_isean1,
    yw_kck_isean2,
    yw_kck_trayquantity,
    yw_kck_islowtemperature,
    yw_kck_takemoneytype,
    yw_kck_isgift,
    yw_kck_pricebelttype,
    yw_kck_basematerielretailprice,
    yw_kck_promanageretailprice,
    yw_kck_materielstatus,
    yw_kck_coreitemsclass,
    yw_kck_seasonclass,
    yw_kck_arearangedescibeid,
    yw_kck_arearangedescibe,
    yw_kck_materieldescawakeid,
    yw_kck_materieldescawake,
    yw_kck_forbiddenreason,
    yw_kck_stoppurchasereason,
    yw_kck_pzwhxq,
    yw_kck_zzqx,
    yw_kck_yyzyxkzxq,
    yw_kck_ishealthfoods,
    yw_kck_issellsplitsmallpack,
    yw_kck_isrecordbiglsh,
    yw_kck_comparebillno,
    yw_kck_syguid,
    yw_kck_stopsalereason,
    yw_kck_xq,
    yw_kck_iskeeppricebreed,
    yw_kck_isagreementbreed,
    yw_kck_isvaluablebreed,
    yw_kck_basematerielguideprice,
    yw_kck_ispricesetbyfactory,
    yw_kck_propricemakedate,
    yw_kck_countrylimitpriceadjustdate,
    yw_kck_hyzk,
    yw_kck_requireclass,
    yw_kck_essentialdruglist,
    yw_kck_materiellong,
    yw_kck_materielwidth,
    yw_kck_materielhigh,
    yw_kck_storesrequireclass,
    yw_kck_subdirct,
    yw_kck_ldw,
    yw_kck_issalepromotion,
    yw_kck_isfood,
    yw_kck_c_xs,
    yw_kck_cfflsx,
    yw_kck_wxsy_lb,
    yw_kck_wxsy_imgurl,
    yw_kck_ischeckmedidevices,
    yw_kck_iswholepick,
    yw_kck_c_pasplb,
    yw_kck_splitratio,
    yw_kck_cfhjlsj,
    yw_kck_zlfl,
    yw_kck_zdyhqxrq,
    yw_kck_zl,
    yw_kck_pzwhqsxq,
    yw_kck_wmslb,
    yw_kck_bmfl,
    yw_kck_wmshl,
    yw_kck_sfyyp,
    yw_kck_sfyxp,
    yw_kck_sfxyzp,
    yw_kck_sfyyy,
    yw_kck_mdyhsx,
    yw_kck_light,
    organization_guid,
    organization_code,
    organization_name,
    organization_helpcode,
    organization_fullname,
    organization_notes,
    organization_parentguid,
    organization_isleaf,
    organization_englishname,
    organization_othername,
    organization_organizationtypeguid,
    organization_financecode,
    organization_chtname,
    organization_fullcode,
    organization_accountconnstring,
    organization_isforbidden,
    organization_forbiddendate,
    organization_forbiddenguid,
    organization_organizationtaxrate,
    organization_issenderorganization,
    organization_isdetail,
    organization_subsellpricetype,
    organization_opendate,
    organization_fstartyear,
    organization_fstartperiod,
    organization_fcurryear,
    organization_fcurrperiod,
    organization_isauditing,
    organization_auditingdate,
    organization_auditingguid,
    organization_accountdate,
    organization_accounttime,
    organization_lastaccountdate,
    organization_isaccount,
    organization_subtype,
    organization_subrange,
    organization_subscale,
    organization_competestatustype,
    organization_sellpricestatustype,
    organization_medinsuranceanalysetype,
    organization_addr,
    organization_subdescribe,
    organization_storemanagername,
    organization_storemanagerbirth,
    organization_tel,
    organization_storemanagerinauguralday,
    organization_ishaspiece,
    organization_workage,
    organization_iscitymedinsurance,
    organization_isprovincemedinsurance,
    organization_israilwaymedinsurance,
    organization_enterpriseage,
    organization_ischronicmedinsurance,
    organization_isspecialmedinsurance,
    organization_plandailysaleamount,
    organization_plandailygrossamount,
    organization_preservedailygrossamount,
    organization_yearsaletargetamount,
    organization_yeargrosstargetamount,
    organization_yeargrossratetarget,
    organization_stockmonthlytarget,
    organization_yearfeetarget,
    organization_subskucheckquantity,
    organization_personnelorgcount,
    organization_actualmancount,
    organization_saleclerkcount,
    organization_salepromotercount,
    organization_leasesigndate,
    organization_leasematuritydate,
    organization_buildarea,
    organization_businessarea,
    organization_areauserate,
    organization_storerent,
    organization_dailyrent,
    organization_yeartotalrent,
    organization_yearbusinessrent,
    organization_pxdevoteaim,
    organization_yearsaleperheadaim,
    organization_saleclerkperaim,
    organization_summary,
    organization_subcommisstype,
    organization_isfranchise,
    organization_isdirectnoaddprice,
    organization_paystylegroup,
    organization_printno,
    organization_orgtype,
    organization_id,
    organization_checkstocksubbh,
    organization_foperationcheck,
    organization_lat,
    organization_lng,
    organization_wx_id,
    organization_token,
    organization_functionname,
    organization_openid,
    organization_cloudplatcode,
    organization_cloudentcode,
    organization_cloudentkey,
    organization_branchaccountinfo,
    organization_issy,
    organization_ismeituan,
    organization_isteldelivery,
    organization_isyb,
    organization_zys,
    organization_xys,
    organization_pianqu,
    organization_cwdl,
    organization2_guid,
    organization2_code,
    organization2_name,
    organization2_helpcode,
    organization2_fullname,
    organization2_notes,
    organization2_parentguid,
    organization2_isleaf,
    organization2_englishname,
    organization2_othername,
    organization2_organization2typeguid,
    organization2_financecode,
    organization2_chtname,
    organization2_fullcode,
    organization2_accountconnstring,
    organization2_isforbidden,
    organization2_forbiddendate,
    organization2_forbiddenguid,
    organization2_organization2taxrate,
    organization2_issenderorganization2,
    organization2_isdetail,
    organization2_subsellpricetype,
    organization2_opendate,
    organization2_fstartyear,
    organization2_fstartperiod,
    organization2_fcurryear,
    organization2_fcurrperiod,
    organization2_isauditing,
    organization2_auditingdate,
    organization2_auditingguid,
    organization2_accountdate,
    organization2_accounttime,
    organization2_lastaccountdate,
    organization2_isaccount,
    organization2_subtype,
    organization2_subrange,
    organization2_subscale,
    organization2_competestatustype,
    organization2_sellpricestatustype,
    organization2_medinsuranceanalysetype,
    organization2_addr,
    organization2_subdescribe,
    organization2_storemanagername,
    organization2_storemanagerbirth,
    organization2_tel,
    organization2_storemanagerinauguralday,
    organization2_ishaspiece,
    organization2_workage,
    organization2_iscitymedinsurance,
    organization2_isprovincemedinsurance,
    organization2_israilwaymedinsurance,
    organization2_enterpriseage,
    organization2_ischronicmedinsurance,
    organization2_isspecialmedinsurance,
    organization2_plandailysaleamount,
    organization2_plandailygrossamount,
    organization2_preservedailygrossamount,
    organization2_yearsaletargetamount,
    organization2_yeargrosstargetamount,
    organization2_yeargrossratetarget,
    organization2_stockmonthlytarget,
    organization2_yearfeetarget,
    organization2_subskucheckquantity,
    organization2_personnelorgcount,
    organization2_actualmancount,
    organization2_saleclerkcount,
    organization2_salepromotercount,
    organization2_leasesigndate,
    organization2_leasematuritydate,
    organization2_buildarea,
    organization2_businessarea,
    organization2_areauserate,
    organization2_storerent,
    organization2_dailyrent,
    organization2_yeartotalrent,
    organization2_yearbusinessrent,
    organization2_pxdevoteaim,
    organization2_yearsaleperheadaim,
    organization2_saleclerkperaim,
    organization2_summary,
    organization2_subcommisstype,
    organization2_isfranchise,
    organization2_isdirectnoaddprice,
    organization2_paystylegroup,
    organization2_printno,
    organization2_orgtype,
    organization2_id,
    organization2_checkstocksubbh,
    organization2_foperationcheck,
    organization2_lat,
    organization2_lng,
    organization2_wx_id,
    organization2_token,
    organization2_functionname,
    organization2_openid,
    organization2_cloudplatcode,
    organization2_cloudentcode,
    organization2_cloudentkey,
    organization2_branchaccountinfo,
    organization2_issy,
    organization2_ismeituan,
    organization2_isteldelivery,
    organization2_isyb,
    organization2_zys,
    organization2_xys,
    organization2_pianqu,
    organization2_cwdl,
    gl_ryk_zm,
    gl_ryk_dh,
    gl_ryk_xm,
    gl_ryk_jb,
    gl_ryk_jhed,
    gl_ryk_zdf,
    gl_ryk_clf,
    gl_ryk_gz,
    gl_ryk_jj,
    gl_ryk_qtfy,
    gl_ryk_lxfy,
    gl_ryk_ll1,
    gl_ryk_ll2,
    gl_ryk_ll3,
    gl_ryk_tig,
    gl_ryk_bz,
    gl_ryk_max_je,
    gl_ryk_tcbz,
    gl_ryk_zkxx,
    gl_ryk_ryid,
    gl_ryk_zdxj,
    gl_ryk_km1,
    gl_ryk_km2,
    gl_ryk_km3,
    gl_ryk_km4,
    gl_ryk_km5,
    gl_ryk_fisgmp,
    gl_ryk_jgfa,
    gl_ryk_guid,
    gl_ryk_branchguid,
    gl_ryk_operatortype,
    gl_ryk_termcontroltype,
    gl_ryk_yf_xs_1,
    gl_ryk_beginamount,
    gl_ryk_debitamount,
    gl_ryk_creditamount,
    gl_ryk_endamount,
    gl_ryk_beginpreamount,
    gl_ryk_preamount,
    gl_ryk_paybeginamount,
    gl_ryk_paydebitamount,
    gl_ryk_paycreditamount,
    gl_ryk_payendamount,
    gl_ryk_paybeginpreamount,
    gl_ryk_paypreamount,
    gl_ryk_attribute,
    gl_ryk_employeecompany,
    gl_ryk_isauthtwoclassmentaldrug,
    gl_ryk_isauthminddrug,
    gl_ryk_isauthanaesthetic,
    gl_ryk_isauthmedicaltoxicity,
    gl_ryk_isauthradioactive,
    gl_ryk_isauthisvaccine,
    gl_ryk_isauthdangerchemistry,
    gl_ryk_isauthdiagnosticreagent,
    gl_ryk_isauthstimulant,
    gl_ryk_isauthephedrine,
    gl_ryk_isautheggpreparation,
    gl_ryk_isauthtlhormone,
    gl_ryk_isauthmedicaldevicestype,
    gl_ryk_tel,
    gl_ryk_position,
    gl_ryk_positiondesc,
    gl_ryk_idcode,
    gl_ryk_mobilephone,
    gl_ryk_nationalcode,
    gl_ryk_provincecode,
    gl_ryk_citycode,
    gl_ryk_addr,
    gl_ryk_netcode,
    gl_ryk_email,
    gl_ryk_ismessagereceive,
    gl_ryk_ismarried,
    gl_ryk_sex,
    gl_ryk_birth,
    gl_ryk_age,
    gl_ryk_edulevel,
    gl_ryk_bloodtype,
    gl_ryk_professtitle,
    gl_ryk_clerktype,
    gl_ryk_isforbidden,
    gl_ryk_forbiddenguid,
    gl_ryk_forbiddendate,
    gl_ryk_forbiddenreason,
    gl_ryk_joinworkdate,
    gl_ryk_graduateschool,
    gl_ryk_profession,
    gl_ryk_workstatus,
    gl_ryk_substockid,
    gl_ryk_wmsisexport,
    gl_ryk_wmsexportdate,
    gl_ryk_wmsexportcount,
    newstoreset_parentguid,
    newstoreset_dwlb,
    newstoreset_tjbh,
    newstoreset_mc,
    newstoreset_zjm,
    newstoreset_yhzh,
    newstoreset_zzsh,
    newstoreset_fzr,
    newstoreset_tel,
    newstoreset_zxd,
    newstoreset_gdzb,
    newstoreset_tj_tag,
    newstoreset_kdrq,
    newstoreset_bz,
    newstoreset_zk,
    newstoreset_qyxz,
    newstoreset_frdb,
    newstoreset_info_fzr,
    newstoreset_xsr,
    newstoreset_creditterm,
    newstoreset_pzbh,
    newstoreset_dwlx,
    newstoreset_dwid,
    newstoreset_khh,
    newstoreset_yyzz,
    newstoreset_zzqx,
    newstoreset_txzh,
    newstoreset_email,
    newstoreset_edbz,
    newstoreset_edje,
    newstoreset_csbz,
    newstoreset_bz1,
    newstoreset_bz2,
    newstoreset_bz3,
    newstoreset_bz4,
    newstoreset_bz5,
    newstoreset_yszkid,
    newstoreset_yszkkm,
    newstoreset_km1,
    newstoreset_km2,
    newstoreset_km3,
    newstoreset_km4,
    newstoreset_km5,
    newstoreset_fpath,
    newstoreset_fftppath,
    newstoreset_fpopserver,
    newstoreset_fpopport,
    newstoreset_fpopuser,
    newstoreset_fpoppass,
    newstoreset_fisgmp,
    newstoreset_jgfa,
    newstoreset_guid,
    newstoreset_createdate,
    newstoreset_updatedate,
    newstoreset_c_down_tag,
    newstoreset_fdeleted,
    newstoreset_stopsell,
    newstoreset_inoutstatus,
    newstoreset_branchguid,
    newstoreset_salechannel,
    newstoreset_txzhyxq,
    newstoreset_gspgmpyxq,
    newstoreset_flsx,
    newstoreset_mrjsfs,
    newstoreset_mrxsfs,
    newstoreset_shdz,
    newstoreset_fpdw,
    newstoreset_xxdz,
    newstoreset_yzbm,
    newstoreset_lxr,
    newstoreset_handtel,
    newstoreset_faxtel,
    newstoreset_xykzbz,
    newstoreset_khbz,
    newstoreset_zzjgdmzh,
    newstoreset_swdjz,
    newstoreset_gmpgspzsh,
    newstoreset_gmpgspyxq,
    newstoreset_fzrq,
    newstoreset_fzjg,
    newstoreset_zgbm,
    newstoreset_jjxz,
    newstoreset_zczb,
    newstoreset_jyfs,
    newstoreset_yydz,
    newstoreset_kcrq,
    newstoreset_kcjl,
    newstoreset_kcr,
    newstoreset_qyfzr,
    newstoreset_zlfzr,
    newstoreset_khywy,
    newstoreset_sqwtqsrq,
    newstoreset_sqwtjsrq,
    newstoreset_fzxx1,
    newstoreset_fzxx2,
    newstoreset_fzxx3,
    newstoreset_c_sfhg,
    newstoreset_operatorguid,
    newstoreset_bz6,
    newstoreset_ywyidentity,
    newstoreset_zlzk,
    newstoreset_dw_id,
    newstoreset_taglb,
    newstoreset_gp_nsxz,
    newstoreset_gp_xsya,
    newstoreset_gp_xsyb,
    newstoreset_gp_xsyc,
    newstoreset_khsctgbz,
    newstoreset_khfplx,
    newstoreset_wsxkzh,
    newstoreset_wsxkzxq,
    newstoreset_wxhxpxkzh,
    newstoreset_wxhxpxkxq,
    newstoreset_yljgxkzh,
    newstoreset_yljgxkqx,
    newstoreset_ylqxxkzh,
    newstoreset_ylqxxkqx,
    newstoreset_yslx,
    newstoreset_headcustomerguid,
    newstoreset_zzjgdmzqx,
    newstoreset_swdjzqx,
    newstoreset_zlbzxyh,
    newstoreset_zlbzxyqx,
    newstoreset_termcontroltype,
    newstoreset_arearange,
    newstoreset_checkcostprice,
    newstoreset_medicalinstrumenttype,
    newstoreset_twoclassmentaldrugemploy,
    newstoreset_mentaldrugauthoritybegindate,
    newstoreset_mentaldrugauthorityenddate,
    newstoreset_ephedrineempoly,
    newstoreset_ephedrinebegindate,
    newstoreset_ephedrineenddate,
    newstoreset_dbjtlhormoneemploy,
    newstoreset_dbjtlhormonebegindate,
    newstoreset_dbjtlhormoneenddate,
    newstoreset_paytaxestype,
    newstoreset_tdtype,
    newstoreset_pricetype,
    newstoreset_producelimit,
    newstoreset_periodcontrol,
    newstoreset_selldigit,
    newstoreset_invoiceamount,
    newstoreset_beginamount,
    newstoreset_debitamount,
    newstoreset_creditamount,
    newstoreset_endamount,
    newstoreset_beginpreamount,
    newstoreset_preamount,
    newstoreset_autocode,
    newstoreset_groupascriptioncode,
    newstoreset_attribute1,
    newstoreset_attribute2,
    newstoreset_attribute3,
    newstoreset_controltype,
    newstoreset_addr,
    newstoreset_isgroupenterprise,
    newstoreset_c_hkrq,
    newstoreset_c_jzrq,
    newstoreset_balanceday,
    newstoreset_backday,
    newstoreset_promotiontype,
    newstoreset_noteprintguid,
    newstoreset_printtag,
    newstoreset_noteprintguid2,
    newstoreset_opendate,
    newstoreset_sellpricetype,
    newstoreset_defaultdeliverorg,
    newstoreset_deliverer,
    newstoreset_deliverweek,
    newstoreset_pickoutstockid,
    newstoreset_sendline,
    newstoreset_pickoutorder,
    newstoreset_issplitmidpack,
    newstoreset_xqdaynumber,
    newstoreset_isconfiguredegree,
    newstoreset_autorecordwantgoods,
    newstoreset_subtype,
    newstoreset_subrange,
    newstoreset_subskucheckquantity,
    newstoreset_substockration,
    newstoreset_isauditing,
    newstoreset_auditingdate,
    newstoreset_auditingguid,
    newstoreset_organizationtaxrate,
    newstoreset_sendaddress,
    newstoreset_iscreatesubdept,
    newstoreset_subdeptid,
    newstoreset_subdeptname,
    newstoreset_subdepthelpcode,
    newstoreset_substockid,
    newstoreset_substockname,
    newstoreset_substockhelpcode,
    newstoreset_isjoininstore,
    newstoreset_issumbalancecus,
    newstoreset_shortforcustom,
    newstoreset_fcurryear,
    newstoreset_fcurrperiod,
    newstoreset_healthcertificate,
    newstoreset_healthfoodslimit,
    newstoreset_gspcontroltype,
    newstoreset_checkstocksubbh,
    newstoreset_minday,
    newstoreset_maxday,
    newstoreset_zys,
    newstoreset_xys,
    substoretasksetdetail_guid,
    substoretasksetdetail_substoretasksetguid,
    substoretasksetdetail_year,
    substoretasksetdetail_month,
    substoretasksetdetail_storemancount,
    substoretasksetdetail_storestaffcount,
    substoretasksetdetail_grossprofittarget,
    substoretasksetdetail_saletarget,
    substoretasksetdetail_grossratetarget,
    substoretasksetdetail_stockdaytarget,
    substoretasksetdetail_stockamounttarget,
    substoretasksetdetail_monthstart,
    substoretasksetdetail_monthend,
    substoretasksetdetail_notes,
    substoretasksetdetail_monthsale,
    substoretasksetdetail_monthgrossprofit,
    substoretasksetdetail_monthgrossrate,
    substoretasksetdetail_monthstockamount,
    substoretasksetdetail_monthsourcegrossprofit,
    substoretasksetdetail_monthsourcegrossrate,
    substoretasksetdetail_monthvipsale,
    substoretasksetdetail_montcutomcount,
    substoretasksetdetail_montcutomprcice,
    substoretasksetdetail_montcutomskuprcice,
    substoretasksetdetail_montcutomsku,
    substoretasksetdetail_montcutomunitprcice,
    substoretasksetdetail_subbh,
    dim_member_id,
    dim_member_name,
    dim_member_fdate,
    dim_member_fxb,
    dim_member_fyear,
    dim_member_faddr,
    dim_member_addr,
    dim_member_tele,
    dim_member_lx,
    dim_member_fjksj,
    dim_member_fywsj,
    dim_member_bz,
    dim_member_je,
    dim_member_fdeleted,
    dim_member_ljje,
    dim_member_fforbid,
    dim_member_fcardtype,
    dim_member_frebate,
    dim_member_freserve,
    dim_member_ftime,
    dim_member_fidentityno,
    dim_member_ffamilytele,
    dim_member_fhelpcode,
    dim_member_jgfa,
    dim_member_createdate,
    dim_member_updatedate,
    dim_member_groupcode,
    dim_member_ljfs,
    dim_member_abatedate,
    dim_member_addupmoney,
    dim_member_sumaddupmoney,
    dim_member_jfje,
    dim_member_localaddup,
    dim_member_groupaddup,
    dim_member_localcachin,
    dim_member_groupcachin,
    dim_member_localintegral,
    dim_member_groupintegral,
    dim_member_guid,
    dim_member_localintegralcachin,
    dim_member_groupintegralcachin,
    dim_member_localintegralcach,
    dim_member_groupintegralcach,
    dim_member_branchguid,
    dim_member_xb,
    dim_member_localupdated,
    dim_member_beginconsumeamount,
    dim_member_beginconsumeintegral,
    dim_member_reservecard,
    dim_member_phonenumber,
    dim_member_postalcode,
    dim_member_e_mail,
    dim_member_netcode,
    dim_member_degree,
    dim_member_vocation,
    dim_member_registersuborgan,
    dim_member_servicesperson,
    dim_member_memberarea,
    dim_member_birthdayawoketag,
    dim_member_defaultnotecontent,
    dim_member_latelycaredate,
    dim_member_latelycashindate,
    dim_member_latelyconsumedate,
    dim_member_caretype,
    dim_member_personellike,
    dim_member_memberrememberday,
    dim_member_rememberawoketag,
    dim_member_rememberdescription,
    dim_member_memberawokeday,
    dim_member_awokedayawoketag,
    dim_member_awokedescription,
    dim_member_ismarried,
    dim_member_operatorguid,
    dim_member_hypass,
    dim_member_integralmultiple,
    dim_member_registersuborganname,
    dim_member_factoryno,
    dim_member_bloodtype,
    dim_member_age,
    dim_member_culturedegree,
    dim_member_job,
    dim_member_familymember1,
    dim_member_relationship1,
    dim_member_healthdemand1,
    dim_member_familymember2,
    dim_member_relationship2,
    dim_member_healthdemand2,
    dim_member_anamnesis,
    dim_member_otherthings,
    dim_member_irritabilityhistory,
    dim_member_oftenmateriel,
    dim_member_healthactivity,
    dim_member_clubtype,
    dim_member_isnoteawoke,
    dim_member_clearintegraldate,
    dim_member_ispubliccard,
    dim_member_mnxtillness,
    dim_member_gjjbillness,
    dim_member_xhxtillness,
    dim_member_hxxtillness,
    dim_member_fkjbillness,
    dim_member_xnxgillness,
    dim_member_tnbillness,
    dim_member_eatmaterielnono,
    dim_member_isforlornman,
    dim_member_transactor,
    dim_member_groupcach,
    dim_member_bakfrebate,
    dim_member_nationnalitycode,
    dim_member_provincecode,
    dim_member_citycode,
    dim_member_ismedicare,
    dim_member_nointegral,
    dim_member_cedulatype,
    dim_member_factorytime,
    dim_member_factorydate,
    dim_member_alteroperatorguid,
    dim_member_distance,
    dim_member_memberlable,
    dim_member_isnetcard,
    dim_member_netnumber,
    dim_member_ybid,
    dim_member_yblx,
    dim_member_zq,
    dim_member_age_from_fdate,
    dim_member_age_class,
    item1_guid,
    item1_dataitemtypeguid,
    item1_code,
    item1_name,
    item1_helpcode,
    item1_fullname,
    item1_parentguid,
    item1_isleaf,
    item1_char1,
    item1_char2,
    item1_char3,
    item1_char4,
    item1_char5,
    item1_float1,
    item1_float2,
    item1_float3,
    item1_float4,
    item1_float5,
    item1_chtname,
    item1_englishname,
    item1_issystem,
    item1_notes,
    item1_branchguid,
    item1_isforbidden,
    item1_iscostinvolved,
    item1_billtype,
    item2_guid,
    item2_dataitemtypeguid,
    item2_code,
    item2_name,
    item2_helpcode,
    item2_fullname,
    item2_parentguid,
    item2_isleaf,
    item2_char1,
    item2_char2,
    item2_char3,
    item2_char4,
    item2_char5,
    item2_float1,
    item2_float2,
    item2_float3,
    item2_float4,
    item2_float5,
    item2_chtname,
    item2_englishname,
    item2_issystem,
    item2_notes,
    item2_branchguid,
    item2_isforbidden,
    item2_iscostinvolved,
    item2_billtype,
    item3_guid,
    item3_dataitemtypeguid,
    item3_code,
    item3_name,
    item3_helpcode,
    item3_fullname,
    item3_parentguid,
    item3_isleaf,
    item3_char1,
    item3_char2,
    item3_char3,
    item3_char4,
    item3_char5,
    item3_float1,
    item3_float2,
    item3_float3,
    item3_float4,
    item3_float5,
    item3_chtname,
    item3_englishname,
    item3_issystem,
    item3_notes,
    item3_branchguid,
    item3_isforbidden,
    item3_iscostinvolved,
    item3_billtype,
    kdrq_datatime,
    kdrq_date_time,
    kdrq_date_id,
    kdrq_date_no,
    kdrq_date_desc,
    kdrq_day_of_week,
    kdrq_day_of_week_desc,
    kdrq_day_of_month,
    kdrq_day_of_year,
    kdrq_week_id,
    kdrq_week_desc,
    kdrq_week_of_month,
    kdrq_week_of_year,
    kdrq_first_day_of_week,
    kdrq_first_day_of_week_short,
    kdrq_month_id,
    kdrq_month_no,
    kdrq_month_of_year,
    kdrq_month_desc,
    kdrq_month_long_desc,
    kdrq_first_day_of_month,
    kdrq_quarter_id,
    kdrq_quarter_of_year,
    kdrq_quarter_desc,
    kdrq_quarter_long_desc,
    kdrq_year_id,
    kdrq_year_desc,
    kdrq_first_day_of_year
FROM pharmacy.wide_pharmacy_sales_2019
where dt='20200106';

